### ISSUE TITLE
Collection Download

### ISSUE THREAD

**Issue by leibo123** [leibo123/abotwebsite#1]
- add capability to download a zip of robot images resulting from the search/filter results

- ~~send the proper file(s) when user requests a full download (not the mongodb version)~~

- give guidelines for citing/etc. when user clicks download

**Comment by ekphilli** [comment]
Hey all, just added a comment in Slack chat about this too. Copying here: 
"Echoing Xuan's point earlier, under collection Download 1, it's super important that we ask users to fill out a request form before downloading any images or the CSV file."

**Comment by ekphilli** [comment]
Hey all,
Xuan sent an email today with updated image files. Just wanted to make sure that you got them before closing out this issue.

**Comment by leibo123** [comment]
We ran into a lot of issues with downloading the filtered collection results. (problem lies in dynamically zipping up the desired contents and sending it to the user). Sending a file that already exists (such as a zip of all images or the excel spreadsheet) is easy, we already have that.

Putting this on hold for now since this is taking too much time, but it will hopefully be implemented sometime down the road.

**Comment by leibo123** [comment]
closing this issue because the basic functionality is done now
