### ISSUE TITLE
Style and Responsiveness

### ISSUE THREAD

**Issue by leibo123** [leibo123/abotwebsite#4]
- boxes on home page are sometimes not the same height
  - images in the boxes sometimes overlap with the text when resized
- collection page does not work well with mobile (infinite scroll preferred maybe?)

**Comment by ekphilli** [comment]
One quick change in the estimator. Under the heading "Try the Estimator" 

Remove the write-in blank space so the sentence reads "You will simply say 'yes' or 'no' indicating whether you see each feature in the robot you are testing."

**Comment by Vellichora** [comment]
fixed most styling and responsive issues, just need to put in images for buttons on the collection page: 
-scroll to top button
-filter hide button on mobile view
